before_script:
  - env

image: cinn:0.1

stages:
  - ci
  - build_server

check:prebuilt:
    tags:
        - lite
    stage: ci
    script:
        #- rm -rf ~/.pip
        - pre-commit install

        - git reset --hard HEAD
        # merge the latest code
        - git remote -v
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        #- git fetch origin develop
        #- git merge --no-ff origin/develop

        - ./build.sh check_style
    cache:
        key: check_style
        paths:
            - $CI_USER_DIR/.cache

build:server:
    tags:
        - lite
    stage: build_server
    cache:
        key: server_thirdparty
        paths:
            - build/third_party
            - ~/.ccache
    script:
        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        #- git fetch origin master
        #- git merge --no-ff origin/master
        - ./build.sh ci

    dependencies:
        - check:prebuilt
