before_script:
  - env

image: lite_server

before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-pip git llvm-dev libclang-dev libgmp3-dev g++-4.8 gcc-4.8
  - ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format

stages:
  - ci
  - build_server

check:prebuilt:
    tags:
      - lite
    stage: ci
    script:
        - rm -rf ~/.pip
        - pip3 install pre-commit cpplint
        - pre-commit install

        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - git fetch origin master
        - git merge --no-ff origin/master

        - ./build.sh check_style
    cache:
        key: check_style
        paths:
            - $CI_USER_DIR/.cache

build:server:
    tags:
      - lite

    stage: build_server
    cache:
        key: server_thirdparty
        paths:
            - build/third_party
            - ~/.ccache
    script:
        - apt install ccache

        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - git fetch origin master
        - git merge --no-ff origin/master

        - ./build.sh ci

    dependencies:
        - check:prebuilt
